config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'contact', to: 'contact#index'
  get 'gallery', to: 'gallery#index'
  get 'service', to: 'service#index'
  get 'product', to: 'product#index'
  get 'about',   to: 'about#index'

  post '/send_feedback', to: 'contact#send_feedback'
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def send_feedback
    begin
      FeedbackMailer.send_feedback(params[:email], params[:name], params[:message]).deliver_now
      flash[:notice] = "Feedback Sent Successfully"
    rescue => e
      flash[:alert] = 'There was an error sending your feedback please try again.'
    end
    redirect_to root_path
  end
end

app/controllers/gallery_controller.rb
require "#{Rails.root}/lib/services/image_shack.rb"

class GalleryController < ApplicationController
  include ImageShack

  def index
    @album_hash = {}
    image_shack_images.each do |image|
      image_hash = {}
      direct_link = image['direct_link']
      image_hash[:src] = direct_link
      image_hash[:description] = image['description']
      image_hash[:thumb] = thumbnail(direct_link)
      album = image['album']
      if @album_hash.has_key?(album['id'])
        @album_hash[album['id']][:images] << image_hash
      else
        @album_hash[album['id']] = { name: album['title'], images: [] }
        @album_hash[album['id']][:images] << image_hash
      end
    end
  end
end

app/controllers/home_controller.rb
require "#{Rails.root}/lib/services/image_shack.rb"

class HomeController < ApplicationController
  include ImageShack
  def index
    @images = []
    album = image_shack_albums.find {|x| x['id'] == ENV['image_shack_main_album'] }
    unless album.nil?
      album['images'].each do |img|
        image_hash = {}
        image_hash[:src] = img['direct_link']
        @images << image_hash
      end
    end
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(*controllers)
    if params[:action] == 'index'
      controllers.include?(params[:controller]) ? 'active' : ''
    else
      controllers.first == ("#{params[:controller]}/#{params[:action]}") ? 'active' : ''
    end
  end

  def flash_class(level)
    case level
      when :notice then
        'info'
      when :error then
        'error'
      when :alert then
        'warning'
    end
  end
end

app/views/about/index.html.haml
.container
  .row
    .col-xs-12.col-md-3
      %h3 Our Locations
      %address
        %strong.underline Draper
        %br
        = fa_icon 'map-marker', text: 'Draper, UT - Call For Appointment'
        = fa_icon 'phone', text: '801-576-1985'
        %br
      %address
        %strong.underline St. George Showroom
        %br
        = fa_icon 'map-marker', text: '1240 East 100 South Suite 104'
        %br
        %span St. George UT, 84095
        %br
        = fa_icon 'phone', text: '(435) 673-7777'
    .col-xs-12.col-md-8
      %h3 Showroom Location
      #map{:style => "width: 100%; height: 200px;"}
  .col-xs-12
    %hr
  .row
    .col-xs-12.col-md-9
      %h3 About Us
      %p.lead LED Holdings Inc is the Home Technology and Entertainment Systems Company that provides affordable, cutting-edge products and service. With +20 years of experience, we offer you the product knowledge and expertise to design, install and service the project of your dreams. Our employees are not only home technology experts but are also licensed electricians, a rarity in the industry.
      %p.lead At LED we know your home is where families are raised memories are made. Our contribution to your home will last long after we have finished your install. For this reason, we strive for quality not only in our labor but in our products. We only provide the highest quality products to give you the best experience possible. With all our offerings from home automation to home entertainment systems, we know we can provide with the value you are looking for.
      %p.lead LED Holdings Inc brings you the best in Home Automation and Entertainment Systems. Whatever you can imagine we will be with you throughout the design, install, and follow up process. Reach out to us today to begin your experience. We are conveniently located in Draper and Saint George Utah.
    .col-xs-12.col-md-3
      %h3 Showroom Hours
      %table.table.table-hover
        %thead
          %tr
            %th Day
            %th Time
        %tbody
          - ['Monday', 'Tuesday', 'Wednesday', 'Thursday'].each do |day|
            %tr.success
              %td
                = day.capitalize
              %td
                9:00 AM
                to
                4:00 PM
          %tr.success
            %td Friday
            %td By Appointment
          %tr.danger
            %td Saturday
            %td Closed
          %tr.danger
            %td Sunday
            %td Closed

app/views/contact/_contact_modal.html.haml
#contact_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title Contact Us
      .modal-body
        %form#feedbackForm{:role => "form", method: 'post', action: '/send_feedback'}
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .form-group
            %input#name.form-control{:name => "name", :placeholder => "Name", :type => "text", required: true, :autofocus => true}
              %span.help-block{:style => "display: none;"} Please enter your name.
          .form-group
            %input#email.form-control{:name => "email", :placeholder => "Email Address", :type => "email", required: true}
              %span.help-block{:style => "display: none;"} Please enter a valid e-mail address.
          .form-group
            %textarea#message.form-control{:cols => "100", :name => "message", :placeholder => "Message", :rows => "10", required: true}
            %span.help-block{:style => "display: none;"} Please enter a message.
          .modal-footer
            = link_to "Cancel", :root, class: 'btn btn-default'
            %button#feedbackSubmit.btn.red.pull-right{:type => "submit", data: { "disable-with" => "Sending..."}} Send Feedback

app/views/gallery/index.html.haml
#gallery_accordion.panel-group.container{role: 'tablist', 'aria-multiselectable' => false}
  - @album_hash.each_with_index do |album, i|
    .panel.panel-default.gallery-accordion.text-center.underline
      - album_id = album.first
      - value = album.last
      .panel-heading.gallery-panel.pointer{role: 'tab', id: "heading_#{album_id}"}
        %h4.panel-title.gallery-title.center
          %a{href: "#collapse_#{album_id}", 'data-toggle' => 'collapse', 'data-parent' => '#gallery_accordion', 'aria-extended' => true, 'aria-controlls' => "collapse_#{album_id}"}
            = value[:name]
      - open = i == 0 ? 'in' : 'closed'
      - images = {}
      .panel-collapse.collapse{role: 'tabpanel', 'aria-labelledby' => "heading_#{album_id}", id: "collapse_#{album_id}", class: open}
        .panel-body
          .carousel.slide.gallery-carousel{'data-ride' => 'carousel', id: "carousel-#{album_id}", 'data-interval' => 'false'}
            .carousel-inner{role: 'listbox'}
              - value[:images].each_with_index do |image, i|
                - active = i == 0 ? 'active' : ''
                - images[i] = image[:thumb]
                .item{class: active}
                  %img.gallery-image{src: "http://#{image[:src]}"}
                  .carousel-caption
                    %p.white
                      = image[:description]
            %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-#{album_id}", :role => "button"}
              %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
              %span.sr-only Previous
            %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-#{album_id}", :role => "button"}
              %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
              %span.sr-only Next
        %ul.thumbnails.elastislide-list{id: "album_thumbs_#{album_id}"}
          - images.each do |key, img|
            %li{'data-target' => "#carousel-#{album_id}", 'data-slide-to' => key}
              %a.img-thumb.pointer{href: '#', 'data-id' => key}
                %img.thumb{src: "//#{img}"}

app/views/home/index.html.haml
.container
  .full-col.col-xs-12
    #home_carousel.carousel.slide{'data-ride' => 'carousel'}
      .carousel-inner{role: 'listbox'}
        .item{class: 'active'}
          %img{src: image_path('great-room-half-open.jpg')}
.clearfix
.col-xs-12.col-md-10.col-md-offset-1
  %hr
  %p.lead UtahLED brings you the best in Home Automation and Entertainment Systems. Whatever you can imagine we will be with you throughout the design, install, and follow up process.  Reach out to us today to begin your experience.  We are located in Draper and Saint George Utah.
  %hr
  %h2.text-center Featured Brand Products
  %hr
  #brand_carousel.brand-carousel.carousel.slide.left{'data-ride' => 'carousel'}
    .carousel-inner{role: 'listbox'}
      .item.active
        %a{href: 'http://www.sonos.com', target: '_blank'}
          %img.brand-logo{src: image_path('sonos-logo.jpg')}
      .item
        %a{href: 'http://www.speakercraft.com', target: '_blank'}
          %img.brand-logo{src: image_path('speakercraft-logo.jpg')}
    %a.left.carousel-control{"data-slide" => "prev", :href => "#brand_carousel", :role => "button"}
      %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#brand_carousel", :role => "button"}
      %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
      %span.sr-only Next
  #brand_carousel_2.brand-carousel.carousel.slide.right{'data-ride' => 'carousel'}
    .carousel-inner{role: 'listbox'}
      .item.active
        %a{href: 'http://www.lutron.com', target: '_blank'}
          %img.brand-logo{src: image_path('lu-logo.jpeg')}
      .item
        %a{href: 'http://www.epson.com', target: '_blank'}
          %img.brand-logo{src: image_path('epson-logo.jpg')}
    %a.left.carousel-control{"data-slide" => "prev", :href => "#brand_carousel_2", :role => "button"}
      %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#brand_carousel_2", :role => "button"}
      %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
      %span.sr-only Next
  #brand_carousel_3.brand-carousel.carousel.slide{'data-ride' => 'carousel'}
    .carousel-inner{role: 'listbox'}
      .item.active
        %a{href: 'http://www.samsung.com', target: '_blank'}
          %img.brand-logo{src: image_path('samsung-logo.jpg')}
      .item
        %a{href: 'http://www.originacoustics.com', target: '_blank'}
          %img.brand-logo{src: image_path('origin-logo.jpeg')}
    %a.left.carousel-control{"data-slide" => "prev", :href => "#brand_carousel_3", :role => "button"}
      %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#brand_carousel_3", :role => "button"}
      %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
      %span.sr-only Next

app/views/layouts/_header.html.haml
.navbar.navbar-default{role: 'navigation'}
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{'data-toggle' => 'collapse', 'data-target' => '#nav-items', type: 'button'}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a{href: '/'}
        %img{src: image_path('utah-led.jpg'), height: 75, width: 150}
      %span{class: 'hidden-s hidden-xs', style: 'display: flex; align-items: center; justify-content: center;'}
        = link_to "https://www.facebook.com/utahled", {target: '_blank'}, class: 'hidden-xs hidden-s' do
          = fa_icon 'facebook-square 3x', class: 'shadow black nav-item'
        = link_to "https://www.instagram.com/utahled", {target: '_blank'}, class: 'hidden-xs hidden-s' do
          = fa_icon 'instagram 3x', class: 'shadow black nav-item' 
        %a.black.no-decoration{href: '#contact_modal', 'data-toggle' => 'modal'}
          = fa_icon "envelope 3x", class: 'pointer', id: 'contact_trigger'
    %h3.logo-label{ class: 'hidden-xs hidden-s', style: 'margin-top: 45px;'}
      %span.label.label-danger PRE-WIRE Specialists
    #nav-items.collapse.navbar-collapse.navbar-right
      %ul.nav.navbar-nav{ class: 'hidden-xs hidden-s', style: 'height: 100px; display: flex; align-items: center; justify-content: center;'}
        %li
          = link_to("Home", '/', class: "nav-item #{active_class('home')}")
        %li
          = link_to("About Us", about_path, class: "nav-item #{active_class('about')}")
        %li
          = link_to("Products", product_path, class: "nav-item #{active_class('product')}")
        %li
          = link_to("Services", service_path, class: "nav-item #{active_class('service')}")
        %li
          = link_to("Gallery", gallery_path, class: "nav-item #{active_class('gallery')}")
        %li
          = render partial: 'layouts/social_media_links', locals: {classes: 'visible-xs visible-s'}
      %ul.nav.navbar-nav{ class: 'visible-xs visible-s' }
        %li
          = link_to("Home", '/', class: "nav-item #{active_class('home')}")
        %li
          = link_to("About Us", about_path, class: "nav-item #{active_class('about')}")
        %li
          = link_to("Products", product_path, class: "nav-item #{active_class('product')}")
        %li
          = link_to("Services", service_path, class: "nav-item #{active_class('service')}")
        %li
          = link_to("Gallery", gallery_path, class: "nav-item #{active_class('gallery')}")
        %li
          = render partial: 'layouts/social_media_links', locals: {classes: 'visible-xs visible-s'}

app/views/layouts/_social_media_links.html.haml
%div{class: classes}
  = link_to "https://www.facebook.com/utahled", {target: '_blank'} do
    = fa_icon 'facebook-square', class: 'complimentary social-nav shadow black nav-item'
  = link_to "https://www.instagram.com/utahled", {target: '_blank'} do
    = fa_icon 'instagram', class: 'complimentary social-nav shadow black nav-item'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UtahLED
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %script{:src => "//maps.google.com/maps/api/js?key=#{ENV['google_maps_api_key']}", :type => "text/javascript"}
    %script{:src => "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js", :type => "text/javascript"}
    / Facebook Pixel Code
    :javascript
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '247785359329930');
        fbq('track', 'PageView');
    %noscript
      %img{:height => "1", :style => "display:none", :width => "1"}>/
      \&#xA0;&#xA0;src="https://www.facebook.com/tr?id=247785359329930=PageView=1"
      \/&gt;
    / End Facebook Pixel Code

  %body
    .container-fluid
      = render partial: 'layouts/header'
      = render :partial => "shared/bflash"
      = yield
      .clearfix
      %hr
      %footer.footer.text-center
        ©
        = Date.today.year
        UtahLED
        \-
        Built By: Jake Sorce
    = render partial: 'contact/contact_modal'

app/views/product/index.html.haml
.row
  %h2.text-center Authorized Products
  %hr
  %h3.text-center.underline Audio Products
  .col-xs-12.col-md-6.col-md-offset-1
    #brand_carousel_1.carousel.slide.left{'data-ride' => 'carousel'}
      .carousel-inner{role: 'listbox'}
        .item.active
          %a{href: 'http://www.sonos.com', target: '_blank'}
            %img.authorized-logo{src: image_path('sonos-logo.jpg')}
          .visible-xs.clearfix
            %hr
        .item
          %a{href: 'http://www.paradigm.com', target: '_blank'}
            %img.authorized-logo{src: image_path('paradigm-logo.jpg')}
          .visible-xs.clearfix
            %hr
      %a.left.carousel-control{"data-slide" => "prev", :href => "#brand_carousel_1", :role => "button"}
        %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
        %span.sr-only Previous
      %a.right.carousel-control{"data-slide" => "next", :href => "#brand_carousel_1", :role => "button"}
        %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
        %span.sr-only Next
  .col-xs-12.col-md-4
    #brand_carousel_2.carousel.slide.left{'data-ride' => 'carousel'}
      .carousel-inner{role: 'listbox'}
        .item.active
          %a{href: 'http://www.originacoustics.com', target: '_blank'}
            %img.authorized-logo{src: image_path('origin-logo.jpeg')}
        .item
          %a{href: 'http://www.speakercraft.com', target: '_blank'}
            %img.authorized-logo{src: image_path('speakercraft-logo.jpg')}
        .item
          %a{href: 'http://www.tdgaudio.com', target: '_blank'}
            %img.authorized-logo{src: image_path('davinci-group-logo.jpeg')}
      %a.left.carousel-control{"data-slide" => "prev", :href => "#brand_carousel_2", :role => "button"}
        %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
        %span.sr-only Previous
      %a.right.carousel-control{"data-slide" => "next", :href => "#brand_carousel_2", :role => "button"}
        %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
        %span.sr-only Next
  .clearfix
  %hr
  %h3.text-center.underline Video Products
  .col-xs-12.col-md-6.col-md-offset-4
    #brand_carousel_3.carousel.slide.left{'data-ride' => 'carousel'}
      .carousel-inner{role: 'listbox'}
        .item.active
          %a{href: 'http://www.samsung.com', target: '_blank'}
            %img.authorized-logo{src: image_path('samsung-logo.jpg')}
        .item
          %a{href: 'http://www.epson.com', target: '_blank'}
            %img.authorized-logo{src: image_path('epson-logo.jpg')}
      %a.left.carousel-control{"data-slide" => "prev", :href => "#brand_carousel_3", :role => "button"}
        %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
        %span.sr-only Previous
      %a.right.carousel-control{"data-slide" => "next", :href => "#brand_carousel_3", :role => "button"}
        %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
        %span.sr-only Next
  .clearfix
  %hr
  %h3.text-center.underline Automation Products
  .col-xs-12.col-md-6.col-md-offset-1
    #brand_carousel_4.carousel.slide.left{'data-ride' => 'carousel'}
      .carousel-inner{role: 'listbox'}
        .item.active
          %a{href: 'http://www.lutron.com/en-US/Residential-Commercial-Solutions/Pages/Residential-Solutions/ShadingSolutions.aspx', target: '_blank'}
            %img.authorized-logo{src: image_path('lu-logo.jpeg')}
          .visible-xs.clearfix
            %hr
        .item
          %a{href: 'http://www.universalremote.com', target: '_blank'}
            %img.authorized-logo{src: image_path('urc-logo.jpeg')}
          .visible-xs.clearfix
            %hr
      %a.left.carousel-control{"data-slide" => "prev", :href => "#brand_carousel_4", :role => "button"}
        %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
        %span.sr-only Previous
      %a.right.carousel-control{"data-slide" => "next", :href => "#brand_carousel_4", :role => "button"}
        %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
        %span.sr-only Next
  .col-xs-12.col-md-4
    #brand_carousel_5.carousel.slide.left{'data-ride' => 'carousel'}
      .carousel-inner{role: 'listbox'}
        .item.active
          %a{href: 'http://www.universalremote.com/solutions/total-control/', target: '_blank'}
            %img.authorized-logo{src: image_path('total-control-logo.jpg')}
        .item
          %a{href: 'http://www.lutron.com', target: '_blank'}
            %img.authorized-logo{src: image_path('lutron-lighting-logo.jpeg')}
      %a.left.carousel-control{"data-slide" => "prev", :href => "#brand_carousel_5", :role => "button"}
        %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
        %span.sr-only Previous
      %a.right.carousel-control{"data-slide" => "next", :href => "#brand_carousel_5", :role => "button"}
        %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
        %span.sr-only Next
  .clearfix
  %hr

app/views/service/index.html.haml
%h2.text-center Services We Offer
%hr
.row
  .col-xs-12.col-sm-6.col-md-5.col-md-offset-1
    .services-box.text-center
      .front
        = image_tag('home-automation-icon.png')
        .lead
          Home Automation
      .back
        .lead
          Home Automation
  .col-xs-12.col-sm-6
    .services-box
      .front
        = image_tag('lighting-controls-icon.png')
        .lead
          Lighting Control
      .back
        .lead
          Lighting Control
  .col-xs-12.hidden-xs
    %hr
  .row
    .col-xs-12.col-sm-6.col-md-4
      .services-box
        .front
          = image_tag('shades-icon.png')
          .lead
            Automated Shades
        .back
          .lead
            Automated Shades
    .col-xs-12.col-sm-6.col-md-4
      .services-box
        .front
          = image_tag('theater-room-icon.png')
          .lead
            Theaters/Multi-Media Rooms
        .back
          .lead
            Theaters/Multi-Media Rooms
    .col-xs-12.col-sm-6.col-md-4
      .services-box
        .front
          = image_tag('distributed-icon.png')
          .lead
            Distributive Audio/Video
        .back
          .lead
            Distributive Audio/Video
  .col-xs-12.hidden-xs
    %hr
  .col-xs-12.col-sm-6.col-md-5.col-md-offset-1
    .services-box
      .front
        = image_tag('security-icon.png')
        .lead
          Surveillance and Security Systems
      .back
        .lead
          Surveillance and Security Systems
  .col-xs-12.col-sm-6
    .services-box
      .front
        = image_tag('vacuum-icon.png')
        .lead
          Central Vacuum
      .back
        .lead
          Central Vacuum

app/views/shared/_bflash.html.haml
- [:notice, :error, :alert].each do |level|
  - unless flash[level].blank?
    %div{:class => "alert text-center #{"alert-#{flash_class(level)}"}"}
      = content_tag :strong, flash[level]